// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhkypiqhdfpmcuwjkoqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoa3lwaXFoZGZwbWN1d2prb3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTMxODEsImV4cCI6MjA2NDk2OTE4MX0.7qwpaJWwRuG-FtgdlCxLb3aPMigohkAbKP1lH5o7KpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);